package models.cards;

public enum SpellCardName {
    MONSTER_REBORN,
    TERRAFORMING,
    POT_OF_GREED,
    RAIGEKI,
    CHANGE_OF_HEART,
    HARPIES_FEATHER_DUSTER,
    SWORDS_OF_REVEALING_LIGHT,
    DARK_HOLE,
    SUPPLY_SQUAD,
    SPELL_ABSORPTION,
    MESSENGER_OF_PEACE,
    TWIN_TWISTERS,
    MYSTICAL_SPACE_TYPHOON,
    RING_OF_DEFENSE,
    YAMI,
    FOREST,
    CLOSED_FOREST,
    UMIIRUKA,
    SWORD_OF_DARK_DESTRUCTION,
    BLACK_PENDANT,
    UNITED_WE_STAND,
    MAGNUM_SHIELD,
    ADVANCED_RITUAL_ART
}
